name: Maven Build and Test

on:
  push:
    branches:
      - main  # You can change this to match your main branch name
  pull_request:
    branches:
      - main  # You can change this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B clean package

    - name: Test with Maven
      run: mvn test

    - name: Save Test Results
      if: always()
      uses: actions/upload-artifact@v2
      # Add your deployment steps here, e.g., deploying to a server, publishing to a repository, etc.
