name: Push File

on:
  push:
    branches:
      - main

jobs:
  push-file:
    runs-on: ubuntu-latest

    steps:
   

    - name: Create or Update File
      run: echo "This is the content of the file." > example-file.txt
